//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C2SR.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("C2SR.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By {0}.
        /// </summary>
        public static string AboutDialog_Author {
            get {
                return ResourceManager.GetString("AboutDialog_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Cytus II Skill Rate.
        /// </summary>
        public static string AboutDialog_Title {
            get {
                return ResourceManager.GetString("AboutDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0} (Beta).
        /// </summary>
        public static string AboutDialog_Version {
            get {
                return ResourceManager.GetString("AboutDialog_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Button_Close {
            get {
                return ResourceManager.GetString("Button_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Button_OK {
            get {
                return ResourceManager.GetString("Button_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist.
        /// </summary>
        public static string MainWindow_Header_Artist {
            get {
                return ResourceManager.GetString("MainWindow_Header_Artist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BPM.
        /// </summary>
        public static string MainWindow_Header_Bpm {
            get {
                return ResourceManager.GetString("MainWindow_Header_Bpm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chapter.
        /// </summary>
        public static string MainWindow_Header_Chapter {
            get {
                return ResourceManager.GetString("MainWindow_Header_Chapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart.
        /// </summary>
        public static string MainWindow_Header_ChartType {
            get {
                return ResourceManager.GetString("MainWindow_Header_ChartType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MM.
        /// </summary>
        public static string MainWindow_Header_IsMM {
            get {
                return ResourceManager.GetString("MainWindow_Header_IsMM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MxM.
        /// </summary>
        public static string MainWindow_Header_IsMxm {
            get {
                return ResourceManager.GetString("MainWindow_Header_IsMxm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string MainWindow_Header_Level {
            get {
                return ResourceManager.GetString("MainWindow_Header_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constant.
        /// </summary>
        public static string MainWindow_Header_LevelConstant {
            get {
                return ResourceManager.GetString("MainWindow_Header_LevelConstant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song Name.
        /// </summary>
        public static string MainWindow_Header_Name {
            get {
                return ResourceManager.GetString("MainWindow_Header_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score.
        /// </summary>
        public static string MainWindow_Header_Score {
            get {
                return ResourceManager.GetString("MainWindow_Header_Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TP.
        /// </summary>
        public static string MainWindow_Header_TP {
            get {
                return ResourceManager.GetString("MainWindow_Header_TP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string MainWindow_Header_Version {
            get {
                return ResourceManager.GetString("MainWindow_Header_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Edit.
        /// </summary>
        public static string MainWindow_Menu_Edit {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cl_ear.
        /// </summary>
        public static string MainWindow_Menu_Edit_Clear {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Edit_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Copy.
        /// </summary>
        public static string MainWindow_Menu_Edit_Copy {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Edit_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cu_t.
        /// </summary>
        public static string MainWindow_Menu_Edit_Cut {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Edit_Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Delete.
        /// </summary>
        public static string MainWindow_Menu_Edit_DeleteSelection {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Edit_DeleteSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Paste.
        /// </summary>
        public static string MainWindow_Menu_Edit_Paste {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Edit_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Redo.
        /// </summary>
        public static string MainWindow_Menu_Edit_Redo {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Edit_Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select _All.
        /// </summary>
        public static string MainWindow_Menu_Edit_SelectAll {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Edit_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Set Value....
        /// </summary>
        public static string MainWindow_Menu_Edit_SetSelection {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Edit_SetSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Undo.
        /// </summary>
        public static string MainWindow_Menu_Edit_Undo {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Edit_Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string MainWindow_Menu_File {
            get {
                return ResourceManager.GetString("MainWindow_Menu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E_xit.
        /// </summary>
        public static string MainWindow_Menu_File_Exit {
            get {
                return ResourceManager.GetString("MainWindow_Menu_File_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _New.
        /// </summary>
        public static string MainWindow_Menu_File_New {
            get {
                return ResourceManager.GetString("MainWindow_Menu_File_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Open....
        /// </summary>
        public static string MainWindow_Menu_File_Open {
            get {
                return ResourceManager.GetString("MainWindow_Menu_File_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Save.
        /// </summary>
        public static string MainWindow_Menu_File_Save {
            get {
                return ResourceManager.GetString("MainWindow_Menu_File_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save _As....
        /// </summary>
        public static string MainWindow_Menu_File_SaveAs {
            get {
                return ResourceManager.GetString("MainWindow_Menu_File_SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_ettings....
        /// </summary>
        public static string MainWindow_Menu_File_Settings {
            get {
                return ResourceManager.GetString("MainWindow_Menu_File_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Help.
        /// </summary>
        public static string MainWindow_Menu_Help {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _About Cytus II Skill Rate....
        /// </summary>
        public static string MainWindow_Menu_Help_About {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Help_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _View.
        /// </summary>
        public static string MainWindow_Menu_View {
            get {
                return ResourceManager.GetString("MainWindow_Menu_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Statistics....
        /// </summary>
        public static string MainWindow_Menu_View_ViewStatistics {
            get {
                return ResourceManager.GetString("MainWindow_Menu_View_ViewStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load file - {0}.
        /// </summary>
        public static string MainWindow_StatusBarText_LoadFailure {
            get {
                return ResourceManager.GetString("MainWindow_StatusBarText_LoadFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded file successfully - {0}.
        /// </summary>
        public static string MainWindow_StatusBarText_LoadSuccess {
            get {
                return ResourceManager.GetString("MainWindow_StatusBarText_LoadSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created a new document.
        /// </summary>
        public static string MainWindow_StatusBarText_NewDocument {
            get {
                return ResourceManager.GetString("MainWindow_StatusBarText_NewDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save file - {0}.
        /// </summary>
        public static string MainWindow_StatusBarText_SaveFailure {
            get {
                return ResourceManager.GetString("MainWindow_StatusBarText_SaveFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved file successfully - {0}.
        /// </summary>
        public static string MainWindow_StatusBarText_SaveSuccess {
            get {
                return ResourceManager.GetString("MainWindow_StatusBarText_SaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Score: {0} ({1}).
        /// </summary>
        public static string MainWindow_TotalScoreText {
            get {
                return ResourceManager.GetString("MainWindow_TotalScoreText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while loading the file..
        /// </summary>
        public static string MessageBox_Error_Load {
            get {
                return ResourceManager.GetString("MessageBox_Error_Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while saving the file..
        /// </summary>
        public static string MessageBox_Error_Save {
            get {
                return ResourceManager.GetString("MessageBox_Error_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while starting the application. Some essential data files may be removed or damaged..
        /// </summary>
        public static string MessageBox_Error_Startup {
            get {
                return ResourceManager.GetString("MessageBox_Error_Startup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language changes will be applied after restarting the application..
        /// </summary>
        public static string MessageBox_LanguageChanged {
            get {
                return ResourceManager.GetString("MessageBox_LanguageChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes to the current document? All unsaved data will be discarded..
        /// </summary>
        public static string MessageBox_QuerySaveChanges {
            get {
                return ResourceManager.GetString("MessageBox_QuerySaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string OpenFileDialog_Title {
            get {
                return ResourceManager.GetString("OpenFileDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unranked.
        /// </summary>
        public static string Rank_Unranked {
            get {
                return ResourceManager.GetString("Rank_Unranked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As.
        /// </summary>
        public static string SaveFileDialog_Title {
            get {
                return ResourceManager.GetString("SaveFileDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string SettingsDialog_General {
            get {
                return ResourceManager.GetString("SettingsDialog_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        public static string SettingsDialog_General_Language {
            get {
                return ResourceManager.GetString("SettingsDialog_General_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string SettingsDialog_General_Language_enUS {
            get {
                return ResourceManager.GetString("SettingsDialog_General_Language_enUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日本語.
        /// </summary>
        public static string SettingsDialog_General_Language_jaJP {
            get {
                return ResourceManager.GetString("SettingsDialog_General_Language_jaJP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 한국어.
        /// </summary>
        public static string SettingsDialog_General_Language_koKR {
            get {
                return ResourceManager.GetString("SettingsDialog_General_Language_koKR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Startup:.
        /// </summary>
        public static string SettingsDialog_General_StartupAction {
            get {
                return ResourceManager.GetString("SettingsDialog_General_StartupAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New File.
        /// </summary>
        public static string SettingsDialog_General_StartupAction_NewDocument {
            get {
                return ResourceManager.GetString("SettingsDialog_General_StartupAction_NewDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Last File.
        /// </summary>
        public static string SettingsDialog_General_StartupAction_OpenLastDocument {
            get {
                return ResourceManager.GetString("SettingsDialog_General_StartupAction_OpenLastDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsDialog_Title {
            get {
                return ResourceManager.GetString("SettingsDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UI.
        /// </summary>
        public static string SettingsDialog_UI {
            get {
                return ResourceManager.GetString("SettingsDialog_UI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Million Master Achieved.
        /// </summary>
        public static string SetValueDialog_IsMM {
            get {
                return ResourceManager.GetString("SetValueDialog_IsMM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Master Achieved.
        /// </summary>
        public static string SetValueDialog_IsMxm {
            get {
                return ResourceManager.GetString("SetValueDialog_IsMxm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Million Master Achieved.
        /// </summary>
        public static string SetValueDialog_SetsMM {
            get {
                return ResourceManager.GetString("SetValueDialog_SetsMM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Max Master Achieved.
        /// </summary>
        public static string SetValueDialog_SetsMxm {
            get {
                return ResourceManager.GetString("SetValueDialog_SetsMxm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set TP.
        /// </summary>
        public static string SetValueDialog_SetsTP {
            get {
                return ResourceManager.GetString("SetValueDialog_SetsTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Value.
        /// </summary>
        public static string SetValueDialog_Title {
            get {
                return ResourceManager.GetString("SetValueDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank List.
        /// </summary>
        public static string StatisticsDialog_Ranks {
            get {
                return ResourceManager.GetString("StatisticsDialog_Ranks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} or higher.
        /// </summary>
        public static string StatisticsDialog_RankScore {
            get {
                return ResourceManager.GetString("StatisticsDialog_RankScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string StatisticsDialog_Summary {
            get {
                return ResourceManager.GetString("StatisticsDialog_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string StatisticsDialog_Title {
            get {
                return ResourceManager.GetString("StatisticsDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top 30 Songs.
        /// </summary>
        public static string StatisticsDialog_TopSongs {
            get {
                return ResourceManager.GetString("StatisticsDialog_TopSongs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cytus II Skill Rate.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
